## Change Path

In [1]:
%load_ext autoreload
%autoreload 2

import sys
from pathlib import Path

# Adjust this path to where config.py is located
code_dir = Path("/cluster/work/boeva/lrabuzin/deepcast/src")  # or something relative like ../code
sys.path.append(str(code_dir))

## Compare coding regions

In [3]:
from data_preparation.coding_snps.exon_regions import generate_coding_regions

In [4]:
coding_regions = generate_coding_regions()

13:28:31 - data_preparation.coding_snps.exon_regions - DEBUG - Sequences that don't match chromosomes we are looking at (67):
 ['NC_000023.10', 'NC_000024.9', 'NC_012920.1', 'NT_113889.1', 'NT_113923.1', 'NT_113961.1', 'NT_167208.1', 'NT_167209.1', 'NT_167210.1', 'NT_167211.1', 'NT_167212.1', 'NT_167213.1', 'NT_167214.1', 'NT_167215.1', 'NT_167216.1', 'NT_167217.1', 'NT_167218.1', 'NT_167219.1', 'NT_167220.1', 'NT_167221.1', 'NT_167222.1', 'NT_167223.1', 'NT_167224.1', 'NT_167225.1', 'NT_167226.1', 'NT_167227.1', 'NT_167228.1', 'NT_167229.1', 'NT_167230.1', 'NT_167231.1', 'NT_167232.1', 'NT_167233.1', 'NT_167234.1', 'NT_167235.1', 'NT_167236.1', 'NT_167237.1', 'NT_167238.1', 'NT_167239.1', 'NT_167240.1', 'NT_167241.1', 'NT_167242.1', 'NT_167243.1', 'NW_003571064.2', 'NW_003871098.1', 'NW_003871099.1', 'NW_003871100.1', 'NW_003871101.3', 'NW_003871102.1', 'NW_003871103.3', 'NW_004070877.1', 'NW_004070878.1', 'NW_004070879.1', 'NW_004070880.2', 'NW_004070881.1', 'NW_004070882.1', 'NW_004070883.1', 'NW_004070884.1', 'NW_004070885.1', 'NW_004070886.1', 'NW_004070887.1', 'NW_004070888.1', 'NW_004070889.1', 'NW_004070890.2', 'NW_004070891.1', 'NW_004070892.1', 'NW_004070893.1', 'NW_004166866.1']

In [5]:
coding_regions = coding_regions.drop_duplicates(subset=['chr', 'start', 'end'])

### Load Sophie's coding regions

In [6]:
import pandas as pd
from config import EXON_REGIONS_PATH

In [7]:
exon_snps_sophie = pd.read_csv(EXON_REGIONS_PATH.parent / 'exon_regions_v2_old.csv')

In [8]:
coding_regions_sophie = exon_snps_sophie.drop_duplicates(subset=['chr', 'start', 'end'])

### Compare lists

In [9]:
len(coding_regions)

293747

In [10]:
len(coding_regions_sophie)

269604

In [11]:
common = coding_regions.merge(coding_regions_sophie, how='inner')

269604 269604 293747

In [12]:
diff = coding_regions.merge(common, how='left', indicator=True)

In [13]:
diff

        chr   start     end     _merge
0         1   11874   12227       both
1         1   12613   12721       both
2         1   13221   14409       both
3         1   29321   29370       both
4         1   24738   24891       both
...     ...     ...     ...        ...
293742   21  291381  291416  left_only
293743   21  291241  291286  left_only
293744   21  304605  304719  left_only
293745   21  305562  305957  left_only
293746   21  307068  307252  left_only

[293747 rows x 4 columns]

In [14]:
extra = diff[diff['_merge']=='left_only']

In [19]:
sub_dfs = [sub_df for _, sub_df in extra.groupby('chr')]

In [20]:
len(sub_dfs)

22

In [21]:
for chr, sub_df in extra.groupby('chr'):
    print(f"Chromosome {chr} has {len(sub_df)} extra exon regions")
    print(sub_df.head())

Chromosome 1 has 2080 extra exon regions
        chr   start     end     _merge
271611    1   15660   16348  left_only
271612    1   11109   11380  left_only
271613    1    8107    8159  left_only
271614    1    5292    5390  left_only
271615    1  468241  468683  left_only
Chromosome 2 has 222 extra exon regions
        chr  start   end     _merge
281640    2   6693  7538  left_only
281641    2   7746  8228  left_only
281642    2   8335  8567  left_only
281643    2   1105  1172  left_only
281644    2   3865  3963  left_only
Chromosome 3 has 275 extra exon regions
        chr  start   end     _merge
281674    3   1446  1530  left_only
281675    3   2373  5521  left_only
281676    3   6614  6759  left_only
281677    3   7531  7658  left_only
281678    3   9060  9201  left_only
Chromosome 4 has 235 extra exon regions
        chr  start    end     _merge
269604    4  88200  88375  left_only
269605    4  75488  75675  left_only
269606    4  75049  75288  left_only
269607    4  59869  59956  left_only
269608    4  50562  50619  left_only
Chromosome 5 has 415 extra exon regions
        chr  start    end     _merge
281819    5    942   1053  left_only
281820    5   9520   9583  left_only
281821    5  11382  11569  left_only
281822    5  12388  13338  left_only
281823    5  18066  18221  left_only
Chromosome 6 has 11666 extra exon regions
        chr  start    end     _merge
269620    6   5638   5774  left_only
269621    6    732    885  left_only
269622    6  18307  18589  left_only
269623    6  19432  19585  left_only
269624    6  22302  22401  left_only
Chromosome 7 has 1653 extra exon regions
        chr  start    end     _merge
271605    7  86518  86735  left_only
271606    7  42938  44923  left_only
271607    7  48955  49119  left_only
271608    7  42938  46801  left_only
271609    7  74121  74180  left_only
Chromosome 8 has 584 extra exon regions
        chr  start    end     _merge
282148    8  23124  23187  left_only
282149    8  26026  26123  left_only
282150    8  28702  28768  left_only
282151    8  29718  29877  left_only
282152    8  30245  30358  left_only
Chromosome 9 has 320 extra exon regions
        chr  start    end     _merge
282621    9  35074  35196  left_only
282622    9  34079  34149  left_only
282623    9  33172  33282  left_only
282624    9  32261  32362  left_only
282625    9  31863  31886  left_only
Chromosome 10 has 750 extra exon regions
        chr  start    end     _merge
282861   10   6068   7118  left_only
282862   10  45874  46165  left_only
282863   10  32721  32838  left_only
282864   10  32517  32535  left_only
282865   10  32351  32439  left_only
Chromosome 11 has 700 extra exon regions
        chr   start     end     _merge
284553   11   35043   35718  left_only
284554   11  111296  112324  left_only
284555   11  140359  141421  left_only
284556   11  191765  192685  left_only
284557   11   18697   19399  left_only
Chromosome 12 has 462 extra exon regions
        chr   start     end     _merge
282965   12  103005  103628  left_only
282966   12   60289   60469  left_only
282967   12   36498   36664  left_only
282968   12   34987   35161  left_only
282969   12   31728   31925  left_only
Chromosome 13 has 7 extra exon regions
        chr  start    end     _merge
284690   13   1441   1566  left_only
284691   13   4122   7656  left_only
284692   13   4125   7656  left_only
284693   13   1482   1566  left_only
284694   13  14169  14282  left_only
Chromosome 14 has 418 extra exon regions
        chr  start    end     _merge
291931   14  11606  11624  left_only
291932   14  11627  11638  left_only
291933   14  11640  11747  left_only
291934   14  15545  15634  left_only
291935   14  18219  18344  left_only
Chromosome 15 has 128 extra exon regions
        chr  start    end     _merge
283020   15   3613   4039  left_only
283021   15  45831  46065  left_only
283022   15  44056  44184  left_only
283023   15  42919  42969  left_only
283024   15  42737  42830  left_only
Chromosome 16 has 124 extra exon regions
        chr  start    end     _merge
283124   16  56909  57001  left_only
283125   16  52648  52852  left_only
283126   16  50029  50173  left_only
283127   16  47428  47561  left_only
283128   16  45246  45399  left_only
Chromosome 17 has 1321 extra exon regions
        chr   start     end     _merge
271610   17  116623  119732  left_only
281252   17  125243  125361  left_only
281253   17  122114  122788  left_only
281254   17   98178   98585  left_only
281255   17   97426   97608  left_only
Chromosome 18 has 13 extra exon regions
        chr  start    end     _merge
283576   18  82853  83046  left_only
283577   18  83627  83725  left_only
283578   18  87933  88057  left_only
283579   18  89936  90033  left_only
283580   18  93023  93160  left_only
Chromosome 19 has 2496 extra exon regions
        chr   start     end     _merge
283589   19   15357   16764  left_only
283590   19   28200   29125  left_only
283591   19  113164  113310  left_only
283592   19  129372  129498  left_only
283593   19  130643  130738  left_only
Chromosome 20 has 30 extra exon regions
        chr  start    end     _merge
286618   20  19448  19513  left_only
286619   20  18517  19060  left_only
286620   20  16921  17096  left_only
286621   20   9944  10069  left_only
286622   20   9352   9439  left_only
Chromosome 21 has 97 extra exon regions
        chr  start    end     _merge
283649   21   6963   7080  left_only
283650   21   9298   9353  left_only
283651   21  12287  12425  left_only
283652   21  12505  12639  left_only
283653   21  13863  14055  left_only
Chromosome 22 has 147 extra exon regions
        chr  start   end     _merge
283696   22      1  1783  left_only
283697   22   2045  2250  left_only
283698   22   4270  4410  left_only
283699   22   5464  6629  left_only
283700   22   2294  2459  left_only

In [15]:
set(extra['chr'])

{1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22}

### Manual reconstruction (debugging)

In [22]:
from config import GFF_FILE_PATH

columns = ["seqid", "source", "type", "start", "end", "score", "strand", "phase", "attributes"]

if Path(GFF_FILE_PATH).exists():
    gff_df = pd.read_csv(GFF_FILE_PATH, sep="\t", comment='#', header=None, names=columns)

In [33]:
import re

pattern = re.compile(r"chromosome=(\d+)")
chr_dfs: dict[object, tuple[int, pd.DataFrame]] = {}

for seqid, sub_df in gff_df.groupby('seqid'):
    match = pattern.search(sub_df.iloc[0]['attributes'])
    if match:
        chr = int(match.group(1))
        chr_dfs[seqid] = (chr, sub_df)

In [35]:
sequences = {chr:[] for chr in range(1, 23)}

for seqid, (chr, sub_df) in chr_dfs.items():
    sequences[chr].append((chr, len(sub_df), seqid))
    # print(sub_df.columns)
    # print(sub_df.iloc[0].loc['seqid'])
    # print(f"Chromosome {chr}: length {len(sub_df)} seqid {sub_df['seqid']}")

In [36]:
sequences

{1: [(1, 170441, 'NC_000001.10'),
  (1, 1, 'NT_113878.1'),
  (1, 67, 'NT_167207.1'),
  (1, 36, 'NW_003315903.1'),
  (1, 4, 'NW_003315904.1'),
  (1, 221, 'NW_003315905.1'),
  (1, 504, 'NW_003315906.1'),
  (1, 128, 'NW_003315907.1'),
  (1, 163, 'NW_003571030.1'),
  (1, 13179, 'NW_003871055.3'),
  (1, 643, 'NW_003871056.3'),
  (1, 831, 'NW_003871057.1'),
  (1, 4, 'NW_004070863.1'),
  (1, 7, 'NW_004070864.2'),
  (1, 10, 'NW_004070865.1')],
 2: [(2, 142057, 'NC_000002.11'),
  (2, 19, 'NW_003315908.1'),
  (2, 208, 'NW_003315909.1'),
  (2, 48, 'NW_003571031.1'),
  (2, 118, 'NW_003571032.1'),
  (2, 99, 'NW_003571033.2'),
  (2, 413, 'NW_004504299.1')],
 3: [(3, 126346, 'NC_000003.11'),
  (3, 683, 'NW_003315910.1'),
  (3, 75, 'NW_003315911.1'),
  (3, 222, 'NW_003315912.1'),
  (3, 22, 'NW_003315913.1'),
  (3, 23, 'NW_003871058.1'),
  (3, 531, 'NW_003871059.1'),
  (3, 168, 'NW_003871060.1'),
  (3, 479, 'NW_004775426.1')],
 4: [(4, 77460, 'NC_000004.11'),
  (4, 11, 'NT_113885.1'),
  (4, 29, 'NT_113888.1'),
  (4, 242, 'NT_167250.1'),
  (4, 82, 'NW_003315914.1'),
  (4, 1, 'NW_003315915.1'),
  (4, 1038, 'NW_003315916.1'),
  (4, 134, 'NW_003571034.1'),
  (4, 33, 'NW_003571035.1'),
  (4, 384, 'NW_004775427.1')],
 5: [(5, 80441, 'NC_000005.9'),
  (5, 1945, 'NW_003315917.2'),
  (5, 1, 'NW_003315918.1'),
  (5, 4, 'NW_003315919.1'),
  (5, 1, 'NW_003315920.1'),
  (5, 28, 'NW_003571036.1'),
  (5, 742, 'NW_003871061.1'),
  (5, 344, 'NW_004775428.1')],
 6: [(6, 88772, 'NC_000006.11'),
  (6, 14996, 'NT_113891.2'),
  (6, 4861, 'NT_167244.1'),
  (6, 13348, 'NT_167245.1'),
  (6, 11128, 'NT_167246.1'),
  (6, 13291, 'NT_167247.1'),
  (6, 14677, 'NT_167248.1'),
  (6, 12472, 'NT_167249.1'),
  (6, 5, 'NW_003315921.1'),
  (6, 328, 'NW_003871062.1'),
  (6, 169, 'NW_003871063.1'),
  (6, 71, 'NW_004070866.1'),
  (6, 1, 'NW_004166862.1'),
  (6, 125, 'NW_004504300.1'),
  (6, 20, 'NW_004775429.1')],
 7: [(7, 89177, 'NC_000007.13'),
  (7, 34, 'NT_113901.1'),
  (7, 169, 'NW_003315922.2'),
  (7, 692, 'NW_003571037.1'),
  (7, 28, 'NW_003571038.1'),
  (7, 45, 'NW_003571039.1'),
  (7, 1614, 'NW_003571040.1'),
  (7, 322, 'NW_003571041.1'),
  (7, 5543, 'NW_003871064.1'),
  (7, 653, 'NW_003871065.1'),
  (7, 68, 'NW_004775430.1')],
 8: [(8, 68346, 'NC_000008.10'),
  (8, 1, 'NT_113907.1'),
  (8, 1, 'NT_113909.1'),
  (8, 1472, 'NW_003315923.1'),
  (8, 745, 'NW_003315924.1'),
  (8, 104, 'NW_003571042.1'),
  (8, 88, 'NW_003871066.2'),
  (8, 854, 'NW_004775431.1')],
 9: [(9, 74266, 'NC_000009.11'),
  (9, 1, 'NT_113911.1'),
  (9, 1, 'NT_113914.1'),
  (9, 1, 'NT_113915.1'),
  (9, 1, 'NT_113916.2'),
  (9, 772, 'NW_003315925.1'),
  (9, 102, 'NW_003315926.1'),
  (9, 76, 'NW_003315927.1'),
  (9, 4, 'NW_003315928.1'),
  (9, 39, 'NW_003315929.1'),
  (9, 109, 'NW_003315930.1'),
  (9, 3, 'NW_003315931.1'),
  (9, 254, 'NW_003871067.1'),
  (9, 4, 'NW_004070867.1'),
  (9, 9, 'NW_004070868.1'),
  (9, 115, 'NW_004070869.1'),
  (9, 14, 'NW_004504301.1')],
 10: [(10, 87850, 'NC_000010.10'),
  (10, 382, 'NW_003315932.1'),
  (10, 1, 'NW_003315933.1'),
  (10, 29, 'NW_003315934.1'),
  (10, 240, 'NW_003315935.1'),
  (10, 67, 'NW_003571043.1'),
  (10, 4240, 'NW_003871068.1'),
  (10, 184, 'NW_003871069.1'),
  (10, 335, 'NW_003871070.1'),
  (10, 247, 'NW_003871071.1'),
  (10, 54, 'NW_004070870.1'),
  (10, 689, 'NW_004504302.1'),
  (10, 91, 'NW_004775432.1')],
 11: [(11, 108922, 'NC_000011.9'),
  (11, 1, 'NT_113921.2'),
  (11, 1, 'NW_003315936.1'),
  (11, 35, 'NW_003571045.1'),
  (11, 41, 'NW_003571046.1'),
  (11, 823, 'NW_003871072.2'),
  (11, 61, 'NW_003871073.1'),
  (11, 38, 'NW_003871074.1'),
  (11, 93, 'NW_003871075.1'),
  (11, 983, 'NW_003871076.1'),
  (11, 81, 'NW_003871077.1'),
  (11, 1445, 'NW_003871078.1'),
  (11, 88, 'NW_003871079.1'),
  (11, 1302, 'NW_003871080.1'),
  (11, 365, 'NW_003871081.1'),
  (11, 389, 'NW_003871082.1'),
  (11, 144, 'NW_004070871.1')],
 12: [(12, 96771, 'NC_000012.11'),
  (12, 42, 'NW_003315937.1'),
  (12, 1, 'NW_003315938.1'),
  (12, 66, 'NW_003315939.1'),
  (12, 5, 'NW_003315940.1'),
  (12, 10, 'NW_003315941.1'),
  (12, 99, 'NW_003315942.2'),
  (12, 156, 'NW_003571047.1'),
  (12, 91, 'NW_003571048.1'),
  (12, 91, 'NW_003571049.1'),
  (12, 168, 'NW_003571050.1'),
  (12, 1349, 'NW_003871083.2'),
  (12, 272, 'NW_004504303.2')],
 13: [(13, 31895, 'NC_000013.10'), (13, 25, 'NW_003571051.1')],
 14: [(14, 52748, 'NC_000014.8'), (14, 1546, 'NW_004166863.1')],
 15: [(15, 60333, 'NC_000015.9'),
  (15, 263, 'NW_003315943.1'),
  (15, 481, 'NW_003315944.1'),
  (15, 85, 'NW_003871084.1')],
 16: [(16, 66992, 'NC_000016.9'),
  (16, 172, 'NW_003315945.1'),
  (16, 171, 'NW_003315946.1'),
  (16, 431, 'NW_003871085.1')],
 17: [(17, 87630, 'NC_000017.10'),
  (17, 6, 'NT_113930.1'),
  (17, 1, 'NT_113941.1'),
  (17, 1, 'NT_113943.1'),
  (17, 1, 'NT_113945.1'),
  (17, 2215, 'NT_167251.1'),
  (17, 426, 'NW_003315947.1'),
  (17, 169, 'NW_003315948.2'),
  (17, 487, 'NW_003315949.1'),
  (17, 27, 'NW_003315950.2'),
  (17, 20, 'NW_003315951.1'),
  (17, 114, 'NW_003315952.2'),
  (17, 103, 'NW_003315953.1'),
  (17, 1, 'NW_003315954.1'),
  (17, 12, 'NW_003315955.1'),
  (17, 1221, 'NW_003571052.1'),
  (17, 189, 'NW_003871086.1'),
  (17, 186, 'NW_003871087.1'),
  (17, 711, 'NW_003871088.1'),
  (17, 294, 'NW_003871089.1'),
  (17, 375, 'NW_003871090.1'),
  (17, 239, 'NW_003871091.1'),
  (17, 27, 'NW_003871092.1'),
  (17, 33, 'NW_003871093.1'),
  (17, 124, 'NW_004070872.2'),
  (17, 329, 'NW_004166864.2'),
  (17, 5, 'NW_004775433.1')],
 18: [(18, 34009, 'NC_000018.9'),
  (18, 1, 'NT_113947.1'),
  (18, 37, 'NW_003315956.1'),
  (18, 1, 'NW_003315957.1'),
  (18, 1, 'NW_003315958.1'),
  (18, 6, 'NW_003315959.1'),
  (18, 6, 'NW_003315960.1'),
  (18, 13, 'NW_003315961.1')],
 19: [(19, 87170, 'NC_000019.9'),
  (19, 1, 'NT_113948.1'),
  (19, 1, 'NT_113949.1'),
  (19, 106, 'NW_003315962.1'),
  (19, 734, 'NW_003315963.1'),
  (19, 92, 'NW_003315964.2'),
  (19, 22, 'NW_003315965.1'),
  (19, 95, 'NW_003571053.2'),
  (19, 2739, 'NW_003571054.1'),
  (19, 1735, 'NW_003571055.1'),
  (19, 1228, 'NW_003571056.1'),
  (19, 1225, 'NW_003571057.1'),
  (19, 1229, 'NW_003571058.1'),
  (19, 1273, 'NW_003571059.1'),
  (19, 3013, 'NW_003571060.1'),
  (19, 2357, 'NW_003571061.1'),
  (19, 142, 'NW_003871094.1'),
  (19, 2961, 'NW_004166865.1'),
  (19, 1282, 'NW_004775434.1')],
 20: [(20, 37673, 'NC_000020.10'),
  (20, 4, 'NW_003315966.1'),
  (20, 48, 'NW_003571063.2'),
  (20, 1, 'NW_003871095.1'),
  (20, 14, 'NW_004504304.1')],
 21: [(21, 18202, 'NC_000021.8'),
  (21, 1, 'NT_113950.2'),
  (21, 7, 'NW_003315967.1'),
  (21, 17, 'NW_003315968.1'),
  (21, 52, 'NW_003315969.1'),
  (21, 143, 'NW_003315970.1'),
  (21, 189, 'NW_004775435.1')],
 22: [(22, 37290, 'NC_000022.10'),
  (22, 116, 'NW_003315971.2'),
  (22, 13, 'NW_003315972.1'),
  (22, 237, 'NW_003871096.1'),
  (22, 1, 'NW_004070873.1'),
  (22, 5, 'NW_004070874.1'),
  (22, 7, 'NW_004070875.1'),
  (22, 462, 'NW_004070876.1'),
  (22, 102, 'NW_004504305.1')]}

### Debugged version

In [47]:
from data_preparation.coding_snps.exon_regions import generate_coding_regions

exon_regions_new = generate_coding_regions()

14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NT_113878.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NT_113885.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NT_113888.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NT_113889.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NT_113891.2 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NT_113901.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NT_113907.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NT_113909.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NT_113911.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NT_113914.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NT_113915.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NT_113916.2 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NT_113921.2 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NT_113923.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NT_113930.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NT_113941.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NT_113943.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NT_113945.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NT_113947.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NT_113948.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NT_113949.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NT_113950.2 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NT_113961.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NT_167207.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NT_167208.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NT_167209.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NT_167210.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NT_167211.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NT_167212.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NT_167213.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NT_167214.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NT_167215.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NT_167216.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NT_167217.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NT_167218.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NT_167219.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NT_167220.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NT_167221.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NT_167222.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NT_167223.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NT_167224.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NT_167225.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NT_167226.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NT_167227.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NT_167228.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NT_167229.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NT_167230.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NT_167231.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NT_167232.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NT_167233.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NT_167234.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NT_167235.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NT_167236.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NT_167237.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NT_167238.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NT_167239.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NT_167240.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NT_167241.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NT_167242.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NT_167243.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NT_167244.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NT_167245.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NT_167246.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NT_167247.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NT_167248.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NT_167249.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NT_167250.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NT_167251.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NW_003315903.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NW_003315904.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NW_003315905.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NW_003315906.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NW_003315907.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NW_003315908.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NW_003315909.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NW_003315910.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NW_003315911.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NW_003315912.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NW_003315913.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NW_003315914.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NW_003315915.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NW_003315916.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NW_003315917.2 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NW_003315918.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NW_003315919.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NW_003315920.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NW_003315921.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NW_003315922.2 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NW_003315923.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NW_003315924.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NW_003315925.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NW_003315926.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NW_003315927.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NW_003315928.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NW_003315929.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NW_003315930.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NW_003315931.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NW_003315932.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NW_003315933.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NW_003315934.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NW_003315935.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NW_003315936.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NW_003315937.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NW_003315938.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NW_003315939.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NW_003315940.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NW_003315941.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NW_003315942.2 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NW_003315943.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NW_003315944.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NW_003315945.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NW_003315946.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NW_003315947.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NW_003315948.2 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NW_003315949.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NW_003315950.2 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NW_003315951.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NW_003315952.2 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NW_003315953.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NW_003315954.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NW_003315955.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NW_003315956.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NW_003315957.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NW_003315958.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NW_003315959.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NW_003315960.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NW_003315961.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NW_003315962.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NW_003315963.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NW_003315964.2 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NW_003315965.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NW_003315966.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NW_003315967.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NW_003315968.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NW_003315969.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NW_003315970.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NW_003315971.2 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NW_003315972.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NW_003571030.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NW_003571031.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NW_003571032.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NW_003571033.2 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NW_003571034.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NW_003571035.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NW_003571036.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NW_003571037.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NW_003571038.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NW_003571039.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NW_003571040.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NW_003571041.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NW_003571042.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NW_003571043.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NW_003571045.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NW_003571046.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NW_003571047.1 since it's not reference genome.
14:03:48 - data_preparation.coding_snps.exon_regions - DEBUG - Skipping sequence NW_003571048.1 since it's not reference genome.

In [48]:
exon_regions_new = exon_regions_new.drop_duplicates(subset=['chr', 'start', 'end'])

In [49]:
len(exon_regions_new)

269604

## Test coding snp list generation

In [14]:
from data_preparation.coding_snps.generate_coding_snp_list import generate_coding_snps_list

coding_snps = generate_coding_snps_list()

16:37:39 - data_preparation.coding_snps.exon_regions - DEBUG - Skipped 272 sequences since they're not reference genome:
 ['NT_113878.1', 'NT_113885.1', 'NT_113888.1', 'NT_113889.1', 'NT_113891.2', 'NT_113901.1', 'NT_113907.1', 'NT_113909.1', 'NT_113911.1', 'NT_113914.1', 'NT_113915.1', 'NT_113916.2', 'NT_113921.2', 'NT_113923.1', 'NT_113930.1', 'NT_113941.1', 'NT_113943.1', 'NT_113945.1', 'NT_113947.1', 'NT_113948.1', 'NT_113949.1', 'NT_113950.2', 'NT_113961.1', 'NT_167207.1', 'NT_167208.1', 'NT_167209.1', 'NT_167210.1', 'NT_167211.1', 'NT_167212.1', 'NT_167213.1', 'NT_167214.1', 'NT_167215.1', 'NT_167216.1', 'NT_167217.1', 'NT_167218.1', 'NT_167219.1', 'NT_167220.1', 'NT_167221.1', 'NT_167222.1', 'NT_167223.1', 'NT_167224.1', 'NT_167225.1', 'NT_167226.1', 'NT_167227.1', 'NT_167228.1', 'NT_167229.1', 'NT_167230.1', 'NT_167231.1', 'NT_167232.1', 'NT_167233.1', 'NT_167234.1', 'NT_167235.1', 'NT_167236.1', 'NT_167237.1', 'NT_167238.1', 'NT_167239.1', 'NT_167240.1', 'NT_167241.1', 'NT_167242.1', 'NT_167243.1', 'NT_167244.1', 'NT_167245.1', 'NT_167246.1', 'NT_167247.1', 'NT_167248.1', 'NT_167249.1', 'NT_167250.1', 'NT_167251.1', 'NW_003315903.1', 'NW_003315904.1', 'NW_003315905.1', 'NW_003315906.1', 'NW_003315907.1', 'NW_003315908.1', 'NW_003315909.1', 'NW_003315910.1', 'NW_003315911.1', 'NW_003315912.1', 'NW_003315913.1', 'NW_003315914.1', 'NW_003315915.1', 'NW_003315916.1', 'NW_003315917.2', 'NW_003315918.1', 'NW_003315919.1', 'NW_003315920.1', 'NW_003315921.1', 'NW_003315922.2', 'NW_003315923.1', 'NW_003315924.1', 'NW_003315925.1', 'NW_003315926.1', 'NW_003315927.1', 'NW_003315928.1', 'NW_003315929.1', 'NW_003315930.1', 'NW_003315931.1', 'NW_003315932.1', 'NW_003315933.1', 'NW_003315934.1', 'NW_003315935.1', 'NW_003315936.1', 'NW_003315937.1', 'NW_003315938.1', 'NW_003315939.1', 'NW_003315940.1', 'NW_003315941.1', 'NW_003315942.2', 'NW_003315943.1', 'NW_003315944.1', 'NW_003315945.1', 'NW_003315946.1', 'NW_003315947.1', 'NW_003315948.2', 'NW_003315949.1', 'NW_003315950.2', 'NW_003315951.1', 'NW_003315952.2', 'NW_003315953.1', 'NW_003315954.1', 'NW_003315955.1', 'NW_003315956.1', 'NW_003315957.1', 'NW_003315958.1', 'NW_003315959.1', 'NW_003315960.1', 'NW_003315961.1', 'NW_003315962.1', 'NW_003315963.1', 'NW_003315964.2', 'NW_003315965.1', 'NW_003315966.1', 'NW_003315967.1', 'NW_003315968.1', 'NW_003315969.1', 'NW_003315970.1', 'NW_003315971.2', 'NW_003315972.1', 'NW_003571030.1', 'NW_003571031.1', 'NW_003571032.1', 'NW_003571033.2', 'NW_003571034.1', 'NW_003571035.1', 'NW_003571036.1', 'NW_003571037.1', 'NW_003571038.1', 'NW_003571039.1', 'NW_003571040.1', 'NW_003571041.1', 'NW_003571042.1', 'NW_003571043.1', 'NW_003571045.1', 'NW_003571046.1', 'NW_003571047.1', 'NW_003571048.1', 'NW_003571049.1', 'NW_003571050.1', 'NW_003571051.1', 'NW_003571052.1', 'NW_003571053.2', 'NW_003571054.1', 'NW_003571055.1', 'NW_003571056.1', 'NW_003571057.1', 'NW_003571058.1', 'NW_003571059.1', 'NW_003571060.1', 'NW_003571061.1', 'NW_003571063.2', 'NW_003571064.2', 'NW_003871055.3', 'NW_003871056.3', 'NW_003871057.1', 'NW_003871058.1', 'NW_003871059.1', 'NW_003871060.1', 'NW_003871061.1', 'NW_003871062.1', 'NW_003871063.1', 'NW_003871064.1', 'NW_003871065.1', 'NW_003871066.2', 'NW_003871067.1', 'NW_003871068.1', 'NW_003871069.1', 'NW_003871070.1', 'NW_003871071.1', 'NW_003871072.2', 'NW_003871073.1', 'NW_003871074.1', 'NW_003871075.1', 'NW_003871076.1', 'NW_003871077.1', 'NW_003871078.1', 'NW_003871079.1', 'NW_003871080.1', 'NW_003871081.1', 'NW_003871082.1', 'NW_003871083.2', 'NW_003871084.1', 'NW_003871085.1', 'NW_003871086.1', 'NW_003871087.1', 'NW_003871088.1', 'NW_003871089.1', 'NW_003871090.1', 'NW_003871091.1', 'NW_003871092.1', 'NW_003871093.1', 'NW_003871094.1', 'NW_003871095.1', 'NW_003871096.1', 'NW_003871098.1', 'NW_003871099.1', 'NW_003871100.1', 'NW_003871101.3', 'NW_003871102.1', 'NW_003871103.3', 'NW_004070863.1', 'NW_004070864.2', 'NW_004070865.1', 'NW_004070866.1', 'NW_004070867.1', 'NW_004070868.1', 'NW_004070869.1', 'NW_004070870.1', 'NW_004070871.1', 'NW_004070872.2', 'NW_004070873.1', 'NW_004070874.1', 'NW_004070875.1', 'NW_004070876.1', 'NW_004070877.1', 'NW_004070878.1', 'NW_004070879.1', 'NW_004070880.2', 'NW_004070881.1', 'NW_004070882.1', 'NW_004070883.1', 'NW_004070884.1', 'NW_004070885.1', 'NW_004070886.1', 'NW_004070887.1', 'NW_004070888.1', 'NW_004070889.1', 'NW_004070890.2', 'NW_004070891.1', 'NW_004070892.1', 'NW_004070893.1', 'NW_004166862.1', 'NW_004166863.1', 'NW_004166864.2', 'NW_004166865.1', 'NW_004166866.1', 'NW_004504299.1', 'NW_004504300.1', 'NW_004504301.1', 'NW_004504302.1', 'NW_004504303.2', 'NW_004504304.1', 'NW_004504305.1', 'NW_004775426.1', 'NW_004775427.1', 'NW_004775428.1', 'NW_004775429.1', 'NW_004775430.1', 'NW_004775431.1', 'NW_004775432.1', 'NW_004775433.1', 'NW_004775434.1', 'NW_004775435.1']
16:37:39 - data_preparation.coding_snps.exon_regions - DEBUG - Skipped 3 sequences that don't match chromosomes we are looking at:
 ['NC_000023.10', 'NC_000024.9', 'NC_012920.1']
16:38:41 - data_preparation.coding_snps.in_exon_region_chr - DEBUG - Mask for chromosome 7 contains 40123 coding SNPs out of 1631824 SNPs
16:38:41 - data_preparation.coding_snps.in_exon_region_chr - DEBUG - Mask for chromosome 7 contains 40123 coding SNPs out of 1631824 SNPs
16:38:44 - data_preparation.coding_snps.in_exon_region_chr - DEBUG - Mask for chromosome 5 contains 37071 coding SNPs out of 1796133 SNPs
16:38:44 - data_preparation.coding_snps.in_exon_region_chr - DEBUG - Mask for chromosome 5 contains 37071 coding SNPs out of 1796133 SNPs
16:38:45 - data_preparation.coding_snps.in_exon_region_chr - DEBUG - Mask for chromosome 6 contains 45192 coding SNPs out of 1781874 SNPs
16:38:45 - data_preparation.coding_snps.in_exon_region_chr - DEBUG - Mask for chromosome 6 contains 45192 coding SNPs out of 1781874 SNPs
16:38:49 - data_preparation.coding_snps.in_exon_region_chr - DEBUG - Mask for chromosome 4 contains 32542 coding SNPs out of 2006929 SNPs
16:38:49 - data_preparation.coding_snps.in_exon_region_chr - DEBUG - Mask for chromosome 4 contains 32542 coding SNPs out of 2006929 SNPs
16:38:50 - data_preparation.coding_snps.in_exon_region_chr - DEBUG - Mask for chromosome 3 contains 43863 coding SNPs out of 1977669 SNPs
16:38:50 - data_preparation.coding_snps.in_exon_region_chr - DEBUG - Mask for chromosome 3 contains 43863 coding SNPs out of 1977669 SNPs
16:39:00 - data_preparation.coding_snps.in_exon_region_chr - DEBUG - Mask for chromosome 1 contains 73186 coding SNPs out of 2192420 SNPs
16:39:00 - data_preparation.coding_snps.in_exon_region_chr - DEBUG - Mask for chromosome 1 contains 73186 coding SNPs out of 2192420 SNPs
16:39:04 - data_preparation.coding_snps.in_exon_region_chr - DEBUG - Mask for chromosome 2 contains 51896 coding SNPs out of 2365595 SNPs
16:39:04 - data_preparation.coding_snps.in_exon_region_chr - DEBUG - Mask for chromosome 2 contains 51896 coding SNPs out of 2365595 SNPs
16:39:22 - data_preparation.coding_snps.in_exon_region_chr - DEBUG - Mask for chromosome 9 contains 31036 coding SNPs out of 1213278 SNPs
16:39:22 - data_preparation.coding_snps.in_exon_region_chr - DEBUG - Mask for chromosome 9 contains 31036 coding SNPs out of 1213278 SNPs
16:39:28 - data_preparation.coding_snps.in_exon_region_chr - DEBUG - Mask for chromosome 10 contains 32670 coding SNPs out of 1386898 SNPs
16:39:28 - data_preparation.coding_snps.in_exon_region_chr - DEBUG - Mask for chromosome 10 contains 32670 coding SNPs out of 1386898 SNPs
16:39:30 - data_preparation.coding_snps.in_exon_region_chr - DEBUG - Mask for chromosome 8 contains 29622 coding SNPs out of 1554540 SNPs
16:39:30 - data_preparation.coding_snps.in_exon_region_chr - DEBUG - Mask for chromosome 8 contains 29622 coding SNPs out of 1554540 SNPs
16:39:31 - data_preparation.coding_snps.in_exon_region_chr - DEBUG - Mask for chromosome 13 contains 17876 coding SNPs out of 996834 SNPs
16:39:31 - data_preparation.coding_snps.in_exon_region_chr - DEBUG - Mask for chromosome 13 contains 17876 coding SNPs out of 996834 SNPs
16:39:32 - data_preparation.coding_snps.in_exon_region_chr - DEBUG - Mask for chromosome 12 contains 39041 coding SNPs out of 1329182 SNPs
16:39:32 - data_preparation.coding_snps.in_exon_region_chr - DEBUG - Mask for chromosome 12 contains 39041 coding SNPs out of 1329182 SNPs
16:39:33 - data_preparation.coding_snps.in_exon_region_chr - DEBUG - Mask for chromosome 11 contains 42753 coding SNPs out of 1373405 SNPs
16:39:33 - data_preparation.coding_snps.in_exon_region_chr - DEBUG - Mask for chromosome 11 contains 42753 coding SNPs out of 1373405 SNPs
16:39:33 - data_preparation.coding_snps.in_exon_region_chr - DEBUG - Mask for chromosome 14 contains 27367 coding SNPs out of 905424 SNPs
16:39:33 - data_preparation.coding_snps.in_exon_region_chr - DEBUG - Mask for chromosome 14 contains 27367 coding SNPs out of 905424 SNPs
16:39:45 - data_preparation.coding_snps.in_exon_region_chr - DEBUG - Mask for chromosome 21 contains 10355 coding SNPs out of 386158 SNPs
16:39:45 - data_preparation.coding_snps.in_exon_region_chr - DEBUG - Mask for chromosome 21 contains 10355 coding SNPs out of 386158 SNPs
16:39:47 - data_preparation.coding_snps.in_exon_region_chr - DEBUG - Mask for chromosome 15 contains 28255 coding SNPs out of 823966 SNPs
16:39:47 - data_preparation.coding_snps.in_exon_region_chr - DEBUG - Mask for chromosome 15 contains 28255 coding SNPs out of 823966 SNPs
16:39:52 - data_preparation.coding_snps.in_exon_region_chr - DEBUG - Mask for chromosome 20 contains 19167 coding SNPs out of 612981 SNPs
16:39:52 - data_preparation.coding_snps.in_exon_region_chr - DEBUG - Mask for chromosome 20 contains 19167 coding SNPs out of 612981 SNPs
16:39:52 - data_preparation.coding_snps.in_exon_region_chr - DEBUG - Mask for chromosome 19 contains 46362 coding SNPs out of 637454 SNPs
16:39:52 - data_preparation.coding_snps.in_exon_region_chr - DEBUG - Mask for chromosome 19 contains 46362 coding SNPs out of 637454 SNPs
16:39:55 - data_preparation.coding_snps.in_exon_region_chr - DEBUG - Mask for chromosome 17 contains 39011 coding SNPs out of 777271 SNPs
16:39:55 - data_preparation.coding_snps.in_exon_region_chr - DEBUG - Mask for chromosome 17 contains 39011 coding SNPs out of 777271 SNPs
16:39:55 - data_preparation.coding_snps.in_exon_region_chr - DEBUG - Mask for chromosome 16 contains 30687 coding SNPs out of 890472 SNPs
16:39:55 - data_preparation.coding_snps.in_exon_region_chr - DEBUG - Mask for chromosome 16 contains 30687 coding SNPs out of 890472 SNPs
16:39:55 - data_preparation.coding_snps.in_exon_region_chr - DEBUG - Mask for chromosome 18 contains 15417 coding SNPs out of 781577 SNPs
16:39:55 - data_preparation.coding_snps.in_exon_region_chr - DEBUG - Mask for chromosome 18 contains 15417 coding SNPs out of 781577 SNPs
16:39:57 - data_preparation.coding_snps.in_exon_region_chr - DEBUG - Mask for chromosome 22 contains 19249 coding SNPs out of 384054 SNPs
16:39:57 - data_preparation.coding_snps.in_exon_region_chr - DEBUG - Mask for chromosome 22 contains 19249 coding SNPs out of 384054 SNPs
16:39:57 - data_preparation.coding_snps.in_exon_region - DEBUG - Concatenated lists. Found 752741 coding snps

In [16]:
len(coding_snps)

749317

In [19]:
coding_snps.to_csv(EXON_REGIONS_PATH.parent / 'coding_snps.csv')

### Load Sophie's coding snps

In [5]:
import pandas as pd
from config import EXON_REGIONS_PATH

In [6]:
coding_snps_sophie = pd.read_csv(EXON_REGIONS_PATH)

In [7]:
coding_snps_sophie.duplicated().sum()

np.int64(470)

In [8]:
coding_snps_sophie = coding_snps_sophie.drop_duplicates(subset=['snp'])

In [9]:
len(coding_snps_sophie)

413088

### Compare lists

In [17]:
common = coding_snps.merge(coding_snps_sophie, how='inner')

In [18]:
len(common)

413088

In [93]:
diff = coding_snps.merge(common, how='left', indicator=True)

In [94]:
diff_sophie = coding_snps_sophie.merge(common, how='left', indicator=True)

In [95]:
extra = diff[diff['_merge']=='left_only']

In [96]:
extra_sophie = diff_sophie[diff_sophie['_merge']=='left_only']

In [97]:
extra

                snp     _merge
16      rs144015209  left_only
32      rs546055875  left_only
45      rs200450385  left_only
47      rs184843908  left_only
48      rs189795883  left_only
...             ...        ...
505209  rs369357973  left_only
505211   rs61143038  left_only
505213   rs78671094  left_only
505215  rs137886366  left_only
505216  rs148556672  left_only

[93024 rows x 2 columns]

In [98]:
extra_sophie

                snp     _merge
327252    rs3747243  left_only
327253   rs78060012  left_only
327254    rs9616125  left_only
327255   rs57234197  left_only
327256   rs58819475  left_only
...             ...        ...
328102   rs12628964  left_only
328103  rs117477158  left_only
328104    rs9617018  left_only
328105    rs9617066  left_only
393320          NaN  left_only

[855 rows x 2 columns]

In [114]:
extra_sophie.isna().sum()

snp       1
_merge    0
dtype: int64

In [118]:
extra_sophie.duplicated().sum()

np.int64(0)

In [117]:
extra.isna().sum()

snp       0
_merge    0
dtype: int64

## Deconstruct coding snp list generation

In [68]:

from data_preparation.coding_snps.rs_ids import merge_sumstats_with_reference

coding_regions = generate_coding_regions().drop_duplicates(subset=['chr', 'start', 'end'])

merged_sumstats = merge_sumstats_with_reference('phecode-772.1-both_sexes.tsv.bgz')

14:27:09 - data_preparation.coding_snps.exon_regions - DEBUG - Skipped 272 sequences since they're not reference genome:
 ['NT_113878.1', 'NT_113885.1', 'NT_113888.1', 'NT_113889.1', 'NT_113891.2', 'NT_113901.1', 'NT_113907.1', 'NT_113909.1', 'NT_113911.1', 'NT_113914.1', 'NT_113915.1', 'NT_113916.2', 'NT_113921.2', 'NT_113923.1', 'NT_113930.1', 'NT_113941.1', 'NT_113943.1', 'NT_113945.1', 'NT_113947.1', 'NT_113948.1', 'NT_113949.1', 'NT_113950.2', 'NT_113961.1', 'NT_167207.1', 'NT_167208.1', 'NT_167209.1', 'NT_167210.1', 'NT_167211.1', 'NT_167212.1', 'NT_167213.1', 'NT_167214.1', 'NT_167215.1', 'NT_167216.1', 'NT_167217.1', 'NT_167218.1', 'NT_167219.1', 'NT_167220.1', 'NT_167221.1', 'NT_167222.1', 'NT_167223.1', 'NT_167224.1', 'NT_167225.1', 'NT_167226.1', 'NT_167227.1', 'NT_167228.1', 'NT_167229.1', 'NT_167230.1', 'NT_167231.1', 'NT_167232.1', 'NT_167233.1', 'NT_167234.1', 'NT_167235.1', 'NT_167236.1', 'NT_167237.1', 'NT_167238.1', 'NT_167239.1', 'NT_167240.1', 'NT_167241.1', 'NT_167242.1', 'NT_167243.1', 'NT_167244.1', 'NT_167245.1', 'NT_167246.1', 'NT_167247.1', 'NT_167248.1', 'NT_167249.1', 'NT_167250.1', 'NT_167251.1', 'NW_003315903.1', 'NW_003315904.1', 'NW_003315905.1', 'NW_003315906.1', 'NW_003315907.1', 'NW_003315908.1', 'NW_003315909.1', 'NW_003315910.1', 'NW_003315911.1', 'NW_003315912.1', 'NW_003315913.1', 'NW_003315914.1', 'NW_003315915.1', 'NW_003315916.1', 'NW_003315917.2', 'NW_003315918.1', 'NW_003315919.1', 'NW_003315920.1', 'NW_003315921.1', 'NW_003315922.2', 'NW_003315923.1', 'NW_003315924.1', 'NW_003315925.1', 'NW_003315926.1', 'NW_003315927.1', 'NW_003315928.1', 'NW_003315929.1', 'NW_003315930.1', 'NW_003315931.1', 'NW_003315932.1', 'NW_003315933.1', 'NW_003315934.1', 'NW_003315935.1', 'NW_003315936.1', 'NW_003315937.1', 'NW_003315938.1', 'NW_003315939.1', 'NW_003315940.1', 'NW_003315941.1', 'NW_003315942.2', 'NW_003315943.1', 'NW_003315944.1', 'NW_003315945.1', 'NW_003315946.1', 'NW_003315947.1', 'NW_003315948.2', 'NW_003315949.1', 'NW_003315950.2', 'NW_003315951.1', 'NW_003315952.2', 'NW_003315953.1', 'NW_003315954.1', 'NW_003315955.1', 'NW_003315956.1', 'NW_003315957.1', 'NW_003315958.1', 'NW_003315959.1', 'NW_003315960.1', 'NW_003315961.1', 'NW_003315962.1', 'NW_003315963.1', 'NW_003315964.2', 'NW_003315965.1', 'NW_003315966.1', 'NW_003315967.1', 'NW_003315968.1', 'NW_003315969.1', 'NW_003315970.1', 'NW_003315971.2', 'NW_003315972.1', 'NW_003571030.1', 'NW_003571031.1', 'NW_003571032.1', 'NW_003571033.2', 'NW_003571034.1', 'NW_003571035.1', 'NW_003571036.1', 'NW_003571037.1', 'NW_003571038.1', 'NW_003571039.1', 'NW_003571040.1', 'NW_003571041.1', 'NW_003571042.1', 'NW_003571043.1', 'NW_003571045.1', 'NW_003571046.1', 'NW_003571047.1', 'NW_003571048.1', 'NW_003571049.1', 'NW_003571050.1', 'NW_003571051.1', 'NW_003571052.1', 'NW_003571053.2', 'NW_003571054.1', 'NW_003571055.1', 'NW_003571056.1', 'NW_003571057.1', 'NW_003571058.1', 'NW_003571059.1', 'NW_003571060.1', 'NW_003571061.1', 'NW_003571063.2', 'NW_003571064.2', 'NW_003871055.3', 'NW_003871056.3', 'NW_003871057.1', 'NW_003871058.1', 'NW_003871059.1', 'NW_003871060.1', 'NW_003871061.1', 'NW_003871062.1', 'NW_003871063.1', 'NW_003871064.1', 'NW_003871065.1', 'NW_003871066.2', 'NW_003871067.1', 'NW_003871068.1', 'NW_003871069.1', 'NW_003871070.1', 'NW_003871071.1', 'NW_003871072.2', 'NW_003871073.1', 'NW_003871074.1', 'NW_003871075.1', 'NW_003871076.1', 'NW_003871077.1', 'NW_003871078.1', 'NW_003871079.1', 'NW_003871080.1', 'NW_003871081.1', 'NW_003871082.1', 'NW_003871083.2', 'NW_003871084.1', 'NW_003871085.1', 'NW_003871086.1', 'NW_003871087.1', 'NW_003871088.1', 'NW_003871089.1', 'NW_003871090.1', 'NW_003871091.1', 'NW_003871092.1', 'NW_003871093.1', 'NW_003871094.1', 'NW_003871095.1', 'NW_003871096.1', 'NW_003871098.1', 'NW_003871099.1', 'NW_003871100.1', 'NW_003871101.3', 'NW_003871102.1', 'NW_003871103.3', 'NW_004070863.1', 'NW_004070864.2', 'NW_004070865.1', 'NW_004070866.1', 'NW_004070867.1', 'NW_004070868.1', 'NW_004070869.1', 'NW_004070870.1', 'NW_004070871.1', 'NW_004070872.2', 'NW_004070873.1', 'NW_004070874.1', 'NW_004070875.1', 'NW_004070876.1', 'NW_004070877.1', 'NW_004070878.1', 'NW_004070879.1', 'NW_004070880.2', 'NW_004070881.1', 'NW_004070882.1', 'NW_004070883.1', 'NW_004070884.1', 'NW_004070885.1', 'NW_004070886.1', 'NW_004070887.1', 'NW_004070888.1', 'NW_004070889.1', 'NW_004070890.2', 'NW_004070891.1', 'NW_004070892.1', 'NW_004070893.1', 'NW_004166862.1', 'NW_004166863.1', 'NW_004166864.2', 'NW_004166865.1', 'NW_004166866.1', 'NW_004504299.1', 'NW_004504300.1', 'NW_004504301.1', 'NW_004504302.1', 'NW_004504303.2', 'NW_004504304.1', 'NW_004504305.1', 'NW_004775426.1', 'NW_004775427.1', 'NW_004775428.1', 'NW_004775429.1', 'NW_004775430.1', 'NW_004775431.1', 'NW_004775432.1', 'NW_004775433.1', 'NW_004775434.1', 'NW_004775435.1']
14:27:09 - data_preparation.coding_snps.exon_regions - DEBUG - Skipped 3 sequences that don't match chromosomes we are looking at:
 ['NC_000023.10', 'NC_000024.9', 'NC_012920.1']
14:27:22 - input_output - INFO - Reading in sumstats
14:27:22 - input_output - DEBUG - sumstats path /cluster/work/boeva/lrabuzin/deepcast/data/ukbb_phens/downloads/phecode-772.1-both_sexes.tsv.bgz
14:27:43 - input_output - DEBUG - Read in sumstats with column names:
   chr    pos ref alt  neglog10_pval_EUR
0   1  11063   T   G            0.02194
1   1  13259   G   A            1.54300
2   1  17641   G   A            0.19390
3   1  30741   C   A                NaN
4   1  51427   T   G                NaN
14:27:43 - input_output - DEBUG - Found 5125722 of 28987534 N/A rows in column neglog10_pval_EUR.

In [119]:
merged_sumstats.isna().sum()

chr                        0
pos                        0
ref                        0
alt                        0
neglog10_pval_EUR    4975921
snp                  9193506
dtype: int64

In [122]:
merged_sumstats.dropna(subset=['snp']).isna().sum()

chr                        0
pos                        0
ref                        0
alt                        0
neglog10_pval_EUR    3145449
snp                        0
dtype: int64

In [123]:
extra_sophie.merge(merged_sumstats.dropna(subset=['snp']), how='left', on='snp') # [['snp', 'chr', 'pos']]

             snp     _merge  chr  pos  ref  alt  neglog10_pval_EUR
0      rs3747243  left_only  NaN  NaN  NaN  NaN                NaN
1     rs78060012  left_only  NaN  NaN  NaN  NaN                NaN
2      rs9616125  left_only  NaN  NaN  NaN  NaN                NaN
3     rs57234197  left_only  NaN  NaN  NaN  NaN                NaN
4     rs58819475  left_only  NaN  NaN  NaN  NaN                NaN
..           ...        ...  ...  ...  ...  ...                ...
850   rs12628964  left_only  NaN  NaN  NaN  NaN                NaN
851  rs117477158  left_only  NaN  NaN  NaN  NaN                NaN
852    rs9617018  left_only  NaN  NaN  NaN  NaN                NaN
853    rs9617066  left_only  NaN  NaN  NaN  NaN                NaN
854          NaN  left_only  NaN  NaN  NaN  NaN                NaN

[855 rows x 7 columns]

In [124]:
extra.merge(merged_sumstats.dropna(subset=['snp']), how='left', on='snp') #[['snp', 'pos']]

               snp     _merge  chr       pos ref alt  neglog10_pval_EUR
0      rs144015209  left_only    1    762187   C   T                NaN
1      rs546055875  left_only    1    777516   C   T                NaN
2      rs200450385  left_only    1    792601   T   C                NaN
3      rs184843908  left_only    1    793470   G   A                NaN
4      rs189795883  left_only    1    793553   T   A                NaN
...            ...        ...  ...       ...  ..  ..                ...
93019  rs369357973  left_only   22  46405453   T   C                NaN
93020   rs61143038  left_only   22  46405761   C   T                NaN
93021   rs78671094  left_only   22  46405845   C   T                NaN
93022  rs137886366  left_only   22  46406142   C   G                NaN
93023  rs148556672  left_only   22  46406367   C   T                NaN

[93024 rows x 7 columns]

In [ ]:
from data_preparation.coding_snps.in_exon_region import find_coding_snps

coding_snps = find_coding_snps(merged_sumstats, coding_regions)

Process ForkProcess-651:
Process ForkProcess-646:
Process ForkProcess-648:
Process ForkProcess-647:
Process ForkProcess-649:
Traceback (most recent call last):
  File "/cluster/apps/biomed/boeva/lrabuzin/conda/envs/deepcast_gwas/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
Traceback (most recent call last):
  File "/cluster/apps/biomed/boeva/lrabuzin/conda/envs/deepcast_gwas/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/cluster/apps/biomed/boeva/lrabuzin/conda/envs/deepcast_gwas/lib/python3.11/concurrent/futures/process.py", line 249, in _process_worker
    call_item = call_queue.get(block=True)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^

KeyboardInterrupt:

  File "/cluster/apps/biomed/boeva/lrabuzin/conda/envs/deepcast_gwas/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/cluster/apps/biomed/boeva/lrabuzin/conda/envs/deepcast_gwas/lib/python3.11/multiprocessing/queues.py", line 102, in get
    with self._rlock:
  File "/cluster/apps/biomed/boeva/lrabuzin/conda/envs/deepcast_gwas/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/cluster/apps/biomed/boeva/lrabuzin/conda/envs/deepcast_gwas/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/cluster/apps/biomed/boeva/lrabuzin/conda/envs/deepcast_gwas/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/cluster/apps/biomed/boeva/lrabuzin/conda/envs/deepcast_gwas/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/cluster/apps/biomed/boeva/lrabuzin/conda/envs/deepcast_gwas/lib/python3.11/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/cluster/apps/biomed/boeva/lrabuzin/conda/envs/deepcast_gwas/lib/python3.11/concurrent/futures/process.py", line 249, in _process_worker
    call_item = call_queue.get(block=True)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/apps/biomed/boeva/lrabuzin/conda/envs/deepcast_gwas/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
KeyboardInterrupt
  File "/cluster/apps/biomed/boeva/lrabuzin/conda/envs/deepcast_gwas/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/cluster/apps/biomed/boeva/lrabuzin/conda/envs/deepcast_gwas/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/cluster/apps/biomed/boeva/lrabuzin/conda/envs/deepcast_gwas/lib/python3.11/multiprocessing/queues.py", line 103, in get
    res = self._recv_bytes()
          ^^^^^^^^^^^^^^^^^^
Process ForkProcess-650:
  File "/cluster/apps/biomed/boeva/lrabuzin/conda/envs/deepcast_gwas/lib/python3.11/concurrent/futures/process.py", line 249, in _process_worker
    call_item = call_queue.get(block=True)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/apps/biomed/boeva/lrabuzin/conda/envs/deepcast_gwas/lib/python3.11/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/apps/biomed/boeva/lrabuzin/conda/envs/deepcast_gwas/lib/python3.11/concurrent/futures/process.py", line 249, in _process_worker
    call_item = call_queue.get(block=True)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/apps/biomed/boeva/lrabuzin/conda/envs/deepcast_gwas/lib/python3.11/concurrent/futures/process.py", line 249, in _process_worker
    call_item = call_queue.get(block=True)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/apps/biomed/boeva/lrabuzin/conda/envs/deepcast_gwas/lib/python3.11/multiprocessing/connection.py", line 430, in _recv_bytes
    buf = self._recv(4)
          ^^^^^^^^^^^^^
  File "/cluster/apps/biomed/boeva/lrabuzin/conda/envs/deepcast_gwas/lib/python3.11/multiprocessing/queues.py", line 102, in get
    with self._rlock:
  File "/cluster/apps/biomed/boeva/lrabuzin/conda/envs/deepcast_gwas/lib/python3.11/multiprocessing/queues.py", line 102, in get
    with self._rlock:
  File "/cluster/apps/biomed/boeva/lrabuzin/conda/envs/deepcast_gwas/lib/python3.11/multiprocessing/connection.py", line 395, in _recv
    chunk = read(handle, remaining)
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/apps/biomed/boeva/lrabuzin/conda/envs/deepcast_gwas/lib/python3.11/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
  File "/cluster/apps/biomed/boeva/lrabuzin/conda/envs/deepcast_gwas/lib/python3.11/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
KeyboardInterrupt
Traceback (most recent call last):
  File "/cluster/apps/biomed/boeva/lrabuzin/conda/envs/deepcast_gwas/lib/python3.11/multiprocessing/queues.py", line 102, in get
    with self._rlock:
  File "/cluster/apps/biomed/boeva/lrabuzin/conda/envs/deepcast_gwas/lib/python3.11/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
  File "/cluster/apps/biomed/boeva/lrabuzin/conda/envs/deepcast_gwas/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/cluster/apps/biomed/boeva/lrabuzin/conda/envs/deepcast_gwas/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/cluster/apps/biomed/boeva/lrabuzin/conda/envs/deepcast_gwas/lib/python3.11/concurrent/futures/process.py", line 249, in _process_worker
    call_item = call_queue.get(block=True)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/apps/biomed/boeva/lrabuzin/conda/envs/deepcast_gwas/lib/python3.11/multiprocessing/queues.py", line 102, in get
    with self._rlock:
  File "/cluster/apps/biomed/boeva/lrabuzin/conda/envs/deepcast_gwas/lib/python3.11/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt